# Generated by Django 3.1.1 on 2020-09-14 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200914_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='event',
        ),
        migrations.AddField(
            model_name='bid',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
