# Generated by Django 3.1.1 on 2020-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bid_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='result',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
