# Generated by Django 3.1.1 on 2020-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200915_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
