# Generated by Django 3.1.1 on 2020-09-16 00:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_teams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_league',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
