# Generated by Django 3.1.1 on 2020-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(default='https://res.cloudinary.com/wjclavell/image/upload/v1600537321/P4/bidball_default-user.svg'),
        ),
    ]
