# Generated by Django 3.1.1 on 2020-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_league',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
